services:
  mysqldb:
    image: mysql:8.0
    container_name: movie_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./best_movie 
    container_name: movie_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/movie?allowPublicKeyRetrieval=true&useSSL=false
      DB_USER: root
      DB_PASSWORD: Hv9Mtmjnze7sEumroa4iuXeQyayzG9Cp?Ahk^m^Hai~bi!8g=y
      TMDB_API_KEY: a2d723d0874b7ec3e518cd365b9d418d 

  frontend:
    build: ./frontend 
    container_name: movie_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data: